### ISSUE TITLE
AttributeError: 'Llama' object has no attribute 'ctx'

### ISSUE THREAD

**Issue by Imloopdev** [ngxson/llama-persona#2]
Using python 3.9.5 when running app.py using alpaca-7b-native-enhanced Model I get this error:

llama.cpp: loading model from ./ggml-model-q4_1.bin
error loading model: unexpectedly reached end of file
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    n_ctx=N_CTX,
  File "D:\Work\AI Freind\Venv\lib\site-packages\llama_cpp\llama.py", line 313, in __init__
    assert self.model is not None
AssertionError
Exception ignored in: <function Llama.__del__ at 0x0000020040BE9BF8>
Traceback (most recent call last):
  File "D:\Work\AI Freind\Venv\lib\site-packages\llama_cpp\llama.py", line 1510, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'

I have concluded that it is a problem with the model using the logs but I don't have any idea on how to fix it or where to get a working model from. Any help would be great. Thank you.

**Comment by Imloopdev** [comment]
It was indeed an issue with the model, I just downloaded a bunch from hugging face and checked if one worked. It turn out you need quantisized models for it to work. (Didn't know that cause I am a beginner)
